# Generated by Django 3.0.4 on 2020-06-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=50, verbose_name='Tag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
