# Generated by Django 3.0.4 on 2020-06-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='css_color',
            field=models.CharField(default='null', max_length=50, verbose_name='Css Color for Bootstrap'),
        ),
    ]
