# Generated by Django 3.0.4 on 2020-06-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_css_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsTaskIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('tag_id', models.IntegerField()),
            ],
        ),
    ]
